// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApPJEq2yu1FIHdMpdSMjaTQChKqZkEX3A',
    appId: '1:829298540112:web:8b6c8984d1c95076ffdb55',
    messagingSenderId: '829298540112',
    projectId: 'flutter-maps-d6a2e',
    authDomain: 'flutter-maps-d6a2e.firebaseapp.com',
    storageBucket: 'flutter-maps-d6a2e.appspot.com',
    measurementId: 'G-62NMCN1RNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAuD-Ewp5x4TQ5Hivrd1qzQJ0SeHBN2aM',
    appId: '1:829298540112:android:003b0b874a2941abffdb55',
    messagingSenderId: '829298540112',
    projectId: 'flutter-maps-d6a2e',
    storageBucket: 'flutter-maps-d6a2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7M_2YqmqeblY_Z9lghlptPDRDFC6_1Tc',
    appId: '1:829298540112:ios:47d5f5f634c26870ffdb55',
    messagingSenderId: '829298540112',
    projectId: 'flutter-maps-d6a2e',
    storageBucket: 'flutter-maps-d6a2e.appspot.com',
    androidClientId: '829298540112-qut4e542g4cd0sr9btfjia9eatjuji3s.apps.googleusercontent.com',
    iosClientId: '829298540112-h88pgvd1dq8ca50a32bh6664cnefd7f5.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeSlice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7M_2YqmqeblY_Z9lghlptPDRDFC6_1Tc',
    appId: '1:829298540112:ios:9cfcf31fec1fd598ffdb55',
    messagingSenderId: '829298540112',
    projectId: 'flutter-maps-d6a2e',
    storageBucket: 'flutter-maps-d6a2e.appspot.com',
    androidClientId: '829298540112-qut4e542g4cd0sr9btfjia9eatjuji3s.apps.googleusercontent.com',
    iosClientId: '829298540112-an9nlohs6uv1edbbfuts172ieqo3eml6.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeSlice.RunnerTests',
  );
}
